server:
  port: 8087
spring:
  application:
    name: canary-consumer
      #cloud:
      #inetutils:
      #正则匹配10.0.0开头的网卡ip
    #preferred-networks: 10.0.0
feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: false
  httpclient:
    enabled: false
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  okhttp:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 50
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: 50
      queueSizeRejectionThreshold: 50
  command:
    #全局默认
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
      ## 通过容器指定参数
      #defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
  instance:
    # 使用docker 编排里面的service name，即定义的service名称
    #hostname: ${SERVICE_NAME}
    hostname: localhost
    ## 元数据
    metadata-map:
      version: v1
      #weight: 10
    # 使用ip注册
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #instance-id: ${eureka.instance.hostname}:${server.port}
    #ip-address: ${eureka.instance.hostname}
    ## 心跳和续约
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 10
