server:
  port: 9082
# 配置输出日志
#logging:
  #level:
    #org.springframework.cloud.gateway: TRACE
    #org.springframework.http.server.reactive: DEBUG
    #org.springframework.web.reactive: DEBUG
    #reactor.ipc.netty: DEBUG

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 配置参考：https://www.cnblogs.com/babycomeon/p/11161073.html
spring:
  application:
    name: gateway-reactor-gray
  cloud:
    nacos:
      #nacos配置中心
      config:
        server-addr: localhost:8848
      #nacos注册中心
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # gateway开启服务注册和发现的功能,并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router
          #enabled: true
          # 是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）
          lower-case-service-id: true
          # 全局过滤器组
          filters:
            # #在请求转发之前去掉 gateway的一层路径
            - StripPrefix=1
      routes:
        # 通过访问http://localhost:9082/hello/hello
        # 路由的ID
        - id: hello-consumer
          # 匹配路由的转发地址
          uri: grayLb://hello-consumer
          # 配置该路由的断言，通过PredicateDefinition类进行接收配置。
          predicates:
            - Path=/hello/**